/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package favoritesites;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author honorr
 */
public class EditVisit extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form EditVisit
     */
    public EditVisit(String username) {
        initComponents();
        this.username = username;
    }

    private EditVisit() {
        initComponents();
    }
    private void newFrame() {
        dispose();
        MainFrame mainFrame = new MainFrame(username);
        mainFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        visit_id = new javax.swing.JTextField();
        country = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        season = new javax.swing.JLabel();
        feature = new javax.swing.JLabel();
        comments = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        display_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        country1 = new javax.swing.JLabel();
        year1 = new javax.swing.JLabel();
        city2 = new javax.swing.JLabel();
        season1 = new javax.swing.JLabel();
        feature1 = new javax.swing.JLabel();
        comments1 = new javax.swing.JLabel();
        rating1 = new javax.swing.JLabel();
        country_field = new javax.swing.JTextField();
        city_field = new javax.swing.JTextField();
        year_field = new javax.swing.JTextField();
        feature_field = new javax.swing.JTextField();
        comment_field = new javax.swing.JTextField();
        summer = new javax.swing.JRadioButton();
        spring = new javax.swing.JRadioButton();
        winter = new javax.swing.JRadioButton();
        autumn = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        update_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Visit");

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("EDIT VISIT");

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("<-");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(220, 220, 220)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel2.setText("Write visit id that you want to display");

        visit_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        country.setText("Country :");

        city.setText("City :");

        year.setText("Year Visited :");

        season.setText("Season Visited :");

        feature.setText("Best Feature :");

        comments.setText("Comments :");

        rating.setText("Rating :");

        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("VISIT :");

        display_button.setText("Display");
        display_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_buttonActionPerformed(evt);
            }
        });

        jLabel4.setText("NEW INFORMATIONS :");

        country1.setText("Country :");

        year1.setText("Year Visited :");

        city2.setText("City :");

        season1.setText("Season Visited :");

        feature1.setText("Best Feature :");

        comments1.setText("Comments :");

        rating1.setText("Rating :");

        buttonGroup1.add(summer);
        summer.setText("Summer");

        buttonGroup1.add(spring);
        spring.setText("Spring");

        buttonGroup1.add(winter);
        winter.setText("Winter");

        buttonGroup1.add(autumn);
        autumn.setText("Autumn");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("1");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("2");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("3");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("4");

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setText("5");

        update_button.setText("UPDATE");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(country)
                            .addComponent(year)
                            .addComponent(season)
                            .addComponent(feature)
                            .addComponent(comments)
                            .addComponent(rating)
                            .addComponent(city)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(visit_id, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(display_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(city2)
                            .addComponent(year1)
                            .addComponent(season1)
                            .addComponent(feature1)
                            .addComponent(comments1)
                            .addComponent(rating1)
                            .addComponent(country1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(summer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spring)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(winter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(autumn)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(country_field)
                                        .addComponent(city_field)
                                        .addComponent(year_field)
                                        .addComponent(feature_field, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comment_field, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButton5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButton6)
                                            .addGap(27, 27, 27)
                                            .addComponent(jRadioButton7)
                                            .addGap(35, 35, 35)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(update_button)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jRadioButton8)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(jRadioButton9))))))
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visit_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display_button)
                    .addComponent(country1)
                    .addComponent(country_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(country)
                        .addComponent(city2))
                    .addComponent(city_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city)
                    .addComponent(year1)
                    .addComponent(year_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(year)
                        .addComponent(season1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spring)
                        .addComponent(winter)
                        .addComponent(autumn)
                        .addComponent(summer)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(season)
                    .addComponent(feature1)
                    .addComponent(feature_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feature)
                    .addComponent(comments1)
                    .addComponent(comment_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comments)
                    .addComponent(rating1)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating)
                    .addComponent(update_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        newFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void display_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_buttonActionPerformed
        String id = visit_id.getText();
        Connection databaseConn = Database.connectingDatabase();
        if(databaseConn != null){
           if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the blank");
        }else{
           try{
               PreparedStatement st = (PreparedStatement)databaseConn.prepareStatement("Select * from visits where id=? and username=?");
               st.setInt(1, Integer.parseInt(id));
               st.setString(2, username);
               ResultSet res = st.executeQuery();
               if(res.next()){
                   String countryName = res.getString("country_name");
                   String cityName = res.getString("city_name");
                   int yearVisited = res.getInt("year_visited");
                   String seasonVisited = res.getString("season_visited");
                   String bestFeature = res.getString("feature");
                   String visitComment = res.getString("comment");
                   int visitRating = res.getInt("rating");
                   
                   country.setText("Country : "+countryName);
                   city.setText("City : "+cityName);
                   year.setText("Year Visited : "+yearVisited);
                   season.setText("Season Visited : "+seasonVisited);
                   feature.setText("Best Feature : "+bestFeature);
                   comments.setText("Comments : "+visitComment);
                   rating.setText("Rating : "+visitRating);
                   
                   country_field.setText(countryName);
                   city_field.setText(cityName);
                   year_field.setText(Integer.toString(yearVisited));
                   if(seasonVisited.equals("Spring")){  
                       spring.setSelected(true);
                   } else if(seasonVisited.equals("Winter")){
                       winter.setSelected(true);
                   } else if(seasonVisited.equals("Autumn")){
                       autumn.setSelected(true);
                   } else{
                       summer.setSelected(true);
                   }
                   feature_field.setText(bestFeature);
                   comment_field.setText(visitComment);
                   if(visitRating==1){
                       jRadioButton5.setSelected(true);
                   } else if(visitRating==2){
                       jRadioButton6.setSelected(true);
                   } else if(visitRating==3){
                       jRadioButton7.setSelected(true);
                   } else if(visitRating==4){
                       jRadioButton8.setSelected(true);
                   } else{
                       jRadioButton9.setSelected(true);
                   }
               }else{
                   JOptionPane.showMessageDialog(this, "There is no visit with this ID.");
               }
            }catch(Exception e){
                
            }
           } 
        }  
    }//GEN-LAST:event_display_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        String id = visit_id.getText();
        String seasons;
        String ratingString; 
        String countryName = country_field.getText();
        String cityName = city_field.getText();
        if(summer.isSelected()){
            seasons = summer.getText();
        }else if(winter.isSelected()){
            seasons = winter.getText();
        } else if(autumn.isSelected()){
            seasons = autumn.getText();
        } else{
            seasons = spring.getText();
        }
        String bestFeatureVisit = feature_field.getText();
        String commentVisits = comment_field.getText();
        if(jRadioButton5.isSelected()){
            ratingString = jRadioButton5.getText();
        }else if(jRadioButton6.isSelected()){
            ratingString = jRadioButton6.getText();
        }else if(jRadioButton7.isSelected()){
            ratingString = jRadioButton7.getText();
        }else if(jRadioButton8.isSelected()){
            ratingString = jRadioButton8.getText();
        }else{
            ratingString = jRadioButton9.getText();
        }
        int ratingVisit = Integer.parseInt(ratingString);
        Connection databaseConn = Database.connectingDatabase();
        if(databaseConn !=null){
           if(countryName.isEmpty() || cityName.isEmpty() || year_field.getText().isEmpty() || bestFeatureVisit.isEmpty() || commentVisits.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the blanks");
        }else{
            try{
                PreparedStatement st = (PreparedStatement)databaseConn.prepareStatement("UPDATE visits SET country_name = ?, city_name = ?,year_visited = ?,season_visited = ?,feature = ?,comment = ?,rating = ? WHERE id = ?");
                st.setString(1, countryName);
                st.setString(2, cityName);
                st.setInt(3, Integer.parseInt(year_field.getText()));
                st.setString(4, seasons);
                st.setString(5, bestFeatureVisit);
                st.setString(6, commentVisits);
                st.setInt(7, ratingVisit);
                st.setInt(8, Integer.parseInt(id));
                int res = st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Visit is updated is successfully.");
            }catch(Exception e){

            }
           } 
        }  
    }//GEN-LAST:event_update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditVisit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autumn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel city;
    private javax.swing.JLabel city2;
    private javax.swing.JTextField city_field;
    private javax.swing.JTextField comment_field;
    private javax.swing.JLabel comments;
    private javax.swing.JLabel comments1;
    private javax.swing.JLabel country;
    private javax.swing.JLabel country1;
    private javax.swing.JTextField country_field;
    private javax.swing.JButton display_button;
    private javax.swing.JLabel feature;
    private javax.swing.JLabel feature1;
    private javax.swing.JTextField feature_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JLabel rating;
    private javax.swing.JLabel rating1;
    private javax.swing.JLabel season;
    private javax.swing.JLabel season1;
    private javax.swing.JRadioButton spring;
    private javax.swing.JRadioButton summer;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField visit_id;
    private javax.swing.JRadioButton winter;
    private javax.swing.JLabel year;
    private javax.swing.JLabel year1;
    private javax.swing.JTextField year_field;
    // End of variables declaration//GEN-END:variables

    private String String(int yearVisited) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
